### ISSUE TITLE
Confirmed Logitech K400r

### ISSUE THREAD

**Issue by LucaBongiorni** [phikshun/jackit#11]
Hi guys, just wanted to confirm that it works against Logitech K400r.

P.S. There were some issues with the Ducky parser while injecting 
STRING powershell .....
I will dig on it ASAP.
Cool job!

**Comment by infamy** [comment]
If you send me the sample script, I can work on figuring it out, and adding a test case for it... Most likely a missing character in our HID map.

**Comment by LucaBongiorni** [comment]
Right now I have no access to the right sample, however was a Powershell
Empire Launcher.

PowershellEmpire > usestager launcher listener > execute

I believe was some symbol like - or = breaking the parser. I didn't check
further since I was in a hurry... but u got the point ;)

On Jul 15, 2016 5:48 PM, "Alex Harvey" <notifications@github.com> wrote:

If you send me the sample script, I can work on figuring it out, and adding
a test case for it... Most likely a missing character in our HID map.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/phikshun/jackit/issues/11#issuecomment-232972118>, or mute
the thread

**Comment by phikshun** [comment]
I tested the default Empire stager and added some additional optimization/guidance on the wiki. The default stager worked during my testing.

Luca, this is likely caused by your keyboard layout. Currently the tool assumes you're using a default US keyboard layout. Can I ask what keyboard layout your target is configured to use?

If you'd rather not say, that's okay. I'll be working on adding different layouts this weekend. The only reason I ask is so that you can help us test (we only have standard English keyboards).

**Comment by LucaBongiorni** [comment]
Cool thanks for the hints!

I was testing only for 5 mins my colleague's keyboard, so I didn't have
much time to play with it.
The layout was US and besides empire's issue... I was getting weird issues
with the command STRING ad well...

Example, I had to write "ccalc" in the payload below.. since for some
reasons with one c, it was not getting typed...
...
STRING ccalc
ENTER

Hopefully on Monday I will check for other keyboards to try.

**Comment by phikshun** [comment]
We added a keyboard layout option anyway (--layout). I'll do some reliability testing next -- I suspect we'll need to tune the retransmit and acknowledgement options depending on the device. I'll work on that next.

**Comment by bogiton** [comment]
Wanted to give my two cents for the K400r. I had similar problems while injecting strings with it. Sometimes characters were omitted, but in most cases it was sending a single character (part of the string) indefinitely. I tried setting the layout, which worked fine when targeting windows, but not under Linux.
