### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by RetoSchaedler** [phikshun/jackit#9]
Hi. Other Keyboard layouts then English would be nice for the injection.

**Comment by phikshun** [comment]
Hi Reto, thanks for the feedback. We have a few other features to add first, but we'll get there. In the meantime, feel free to fork the code and create a regionalized version, or submit a pull request.

**Comment by phikshun** [comment]
Hi Reto, we've added an option for keyboard layout (--layout). We parsed the bindings from the USB rubber ducky encoder properties files so we support the same languages. It's still in beta and I haven't tested many of the layouts, so if you get missed characters, an exception, or an incorrect mapping, let us know.

**Comment by RetoSchaedler** [comment]
Hi. Thanks! Keyboard layout works now!
